### ISSUE TITLE
Youtube download error:  undefined method `name' for :net_http:Symbol

### ISSUE THREAD

**Issue by vidhu** [rb2k/viddl-rb#125]
When trying to download a youtube video, I get the following error:

    C:\Users\Vidhu\Desktop>viddl-rb http://www.youtube.com/watch?v=QH2-TGUlwu4
    Loading Plugins
    Plugins loaded: [ViddlRb::ArtePlusSeven, ViddlRb::Bandcamp, ViddlRb::Blip, ViddlRb::Instagram, ViddlRb::Metacafe, ViddlRb::Soundcloud, ViddlRb::Veoh, ViddlRb::Vimeo, ViddlRb::Youtube]
    Will try to extract audio: false.
    Analyzing URL: http://www.youtube.com/watch?v=QH2-TGUlwu4
    Using plugin: ViddlRb::Youtube
    [YOUTUBE] Cipher guess: yes
    Error: undefined method `name' for :net_http:Symbol

    Backtrace:
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/helper/download-helper.rb:64:in `block in     save_file'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/helper/download-helper.rb:57:in `times'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/helper/download-helper.rb:57:in `save_file'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/bin/helper/downloader.rb:14:in `block in download'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/bin/helper/downloader.rb:6:in `each'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/bin/helper/downloader.rb:6:in `download'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/bin/helper/driver.rb:21:in `start'
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/viddl-rb-1.0.8/bin/viddl-rb:32:in `<top (required)>'
    C:/Ruby200/bin/viddl-rb:23:in `load'
    C:/Ruby200/bin/viddl-rb:23:in `<main>'

    C:\Users\Vidhu\Desktop>

**Comment by rb2k** [comment]
Sorry this took so long. Fixes in version 1.1.0.
