### ISSUE TITLE
Soundcloud broken

### ISSUE THREAD

**Issue by philipdesmedt** [rb2k/viddl-rb#127]
I am unable to fetch any Soundcloud audio using Viddl-rb.

Here's the output:

$ viddl-rb https://soundcloud.com/dubstep/midnight-tyrannosaurus-dubloadz-the-soul-scraper-edmcom-exclusive
Loading Plugins
Plugins loaded: [ViddlRb::ArtePlusSeven, ViddlRb::Bandcamp, ViddlRb::Blip, ViddlRb::Instagram, ViddlRb::Metacafe, ViddlRb::Soundcloud, ViddlRb::Veoh, ViddlRb::Vimeo, ViddlRb::Youtube]
Will try to extract audio: false.
Analyzing URL: https://soundcloud.com/dubstep/midnight-tyrannosaurus-dubloadz-the-soul-scraper-edmcom-exclusive
Using plugin: ViddlRb::Soundcloud
Error: Error while running the "ViddlRb::Soundcloud" plugin. Maybe it has to be updated?
Error: undefined method `text' for nil:NilClass.
Backtrace:
(eval):18:in `get_urls_and_filenames'

The script fails on line 18. I haven't had the time to go through this yet. Any ideas?

**Comment by cbe** [comment]
I get the exact same error, any news?

**Comment by rb2k** [comment]
Seems like soundcloud has removed the preload tag we used to grab the file so far.

The plugin has to be rewritten from what I can see. It would probably have to do something like:
https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py

**Comment by rb2k** [comment]
Or probably the easier to understand version over here: https://github.com/013/Soundcloud-Downloader/blob/master/soundcloud-downloader.py

**Comment by rb2k** [comment]
I think this should now work. I pushed version 1.0.9 with the new soundcloud plugin:

```
$ viddl-rb https://soundcloud.com/dubstep/midnight-tyrannosaurus-dubloadz-the-soul-scraper-edmcom-exclusive
Loading Plugins
Plugins loaded: [ViddlRb::ArtePlusSeven, ViddlRb::Bandcamp, ViddlRb::Blip, ViddlRb::Instagram, ViddlRb::Metacafe, ViddlRb::Soundcloud, ViddlRb::Veoh, ViddlRb::Vimeo, ViddlRb::Youtube]
Will try to extract audio: false.
Analyzing URL: https://soundcloud.com/dubstep/midnight-tyrannosaurus-dubloadz-the-soul-scraper-edmcom-exclusive
Using plugin: ViddlRb::Soundcloud
Using aria2c
[#a211ba 3.6MiB/4.2MiB(87%) CN:1 DL:1.4MiB]                                                                                                                     
02/01 18:24:21 [NOTICE] Download complete: /Users/mseeger/temp/Midnight Tyrannosaurus & Dubloadz - The Soul Scraper [EDM.com Exclusive].mp3

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a211ba|OK  |   1.5MiB/s|/Users/mseeger/temp/Midnight Tyrannosaurus & Dubloadz - The Soul Scraper [EDM.com Exclusive].mp3

Status Legend:
(OK):download completed.
Download for Midnight Tyrannosaurus & Dubloadz - The Soul Scraper [EDM.com Exclusive].mp3 successful.
```

**Comment by cbe** [comment]
Works like a charm :+1:
